-- Secure, idempotent payment and electronic receipt support.

alter table public.transacciones_pago
  add column if not exists idempotency_key uuid,
  add column if not exists culqi_token_hash text,
  add column if not exists datos_facturacion jsonb not null default '{}'::jsonb,
  add column if not exists culqi_card_brand text,
  add column if not exists culqi_card_last4 varchar(4),
  add column if not exists culqi_outcome_code text,
  add column if not exists culqi_request_id text,
  add column if not exists verificado_proveedor_en timestamptz;

update public.transacciones_pago
set culqi_token_id = null,
    respuesta_culqi = null
where culqi_token_id is not null
   or respuesta_culqi is not null;

comment on column public.transacciones_pago.culqi_token_id is
  'Legacy only. Culqi tokens must never be persisted.';
comment on column public.transacciones_pago.respuesta_culqi is
  'Legacy only. Full provider responses must never be persisted.';

alter table public.transacciones_pago
  drop constraint if exists transacciones_pago_estado_check;

alter table public.transacciones_pago
  add constraint transacciones_pago_estado_check
  check (estado in ('pendiente', 'procesando', 'pendiente_3ds', 'exitoso', 'fallido', 'reembolsado'));

create unique index if not exists transacciones_pago_idempotency_uidx
  on public.transacciones_pago (idempotency_key)
  where idempotency_key is not null;

create index if not exists transacciones_pago_usuario_estado_idx
  on public.transacciones_pago (id_usuario, estado, creado_en desc);

create table if not exists public.series_comprobante (
  id bigint generated by default as identity primary key,
  ruc_emisor varchar(11) not null,
  tipo_comprobante varchar(7) not null check (tipo_comprobante in ('BOLETA', 'FACTURA')),
  serie varchar(4) not null,
  siguiente_numero bigint not null default 1 check (siguiente_numero > 0),
  actualizado_en timestamptz not null default now(),
  unique (ruc_emisor, tipo_comprobante, serie)
);

create table if not exists public.comprobantes_electronicos (
  id bigint generated by default as identity primary key,
  id_usuario bigint not null references public.usuarios(id),
  id_transaccion bigint not null unique references public.transacciones_pago(id),
  tipo_comprobante varchar(7) not null check (tipo_comprobante in ('BOLETA', 'FACTURA')),
  serie varchar(4) not null,
  numero bigint not null check (numero > 0),
  ambiente_sunat varchar(10) not null default 'beta' check (ambiente_sunat in ('beta', 'production')),
  estado_sunat varchar(16) not null default 'generando'
    check (estado_sunat in ('generando', 'enviado', 'procesando', 'aceptado', 'observado', 'rechazado', 'error')),
  ruc_emisor varchar(11) not null,
  razon_social_emisor text not null,
  tipo_documento_cliente varchar(3) not null,
  numero_documento_cliente varchar(15) not null,
  nombre_cliente text not null,
  direccion_cliente text,
  correo_cliente text not null,
  moneda varchar(3) not null default 'PEN',
  subtotal numeric(12, 2) not null,
  igv numeric(12, 2) not null,
  total numeric(12, 2) not null,
  ruta_xml text,
  ruta_pdf text,
  ruta_cdr text,
  ticket_sunat text,
  codigo_respuesta_sunat text,
  descripcion_respuesta_sunat text,
  resumen_hash text,
  correo_enviado_en timestamptz,
  enviado_sunat_en timestamptz,
  aceptado_sunat_en timestamptz,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (ruc_emisor, tipo_comprobante, serie, numero)
);

create index if not exists comprobantes_usuario_idx
  on public.comprobantes_electronicos (id_usuario, creado_en desc);

create table if not exists public.eventos_webhook_culqi (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_type text,
  culqi_object_id text,
  payload_hash text not null,
  procesado boolean not null default false,
  mensaje_error text,
  recibido_en timestamptz not null default now(),
  procesado_en timestamptz
);

alter table public.series_comprobante enable row level security;
alter table public.comprobantes_electronicos enable row level security;
alter table public.eventos_webhook_culqi enable row level security;

revoke all on table public.series_comprobante from anon, authenticated;
revoke all on table public.comprobantes_electronicos from anon, authenticated;
revoke all on table public.eventos_webhook_culqi from anon, authenticated;
grant all on table public.series_comprobante to service_role;
grant all on table public.comprobantes_electronicos to service_role;
grant all on table public.eventos_webhook_culqi to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'tax-documents',
  'tax-documents',
  false,
  5242880,
  array['application/xml', 'text/xml', 'application/zip', 'application/pdf']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.finalizar_pago_culqi(
  p_transaccion_id bigint,
  p_culqi_charge_id text,
  p_monto numeric,
  p_moneda text,
  p_card_brand text,
  p_card_last4 text,
  p_outcome_code text,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tx public.transacciones_pago%rowtype;
  v_plan public.planes_membresia%rowtype;
  v_membership public.membresias_usuario%rowtype;
  v_now timestamptz := now();
  v_start timestamptz;
  v_end timestamptz;
  v_previous_end timestamptz;
  v_action text;
begin
  select * into v_tx
  from public.transacciones_pago
  where id = p_transaccion_id
  for update;

  if not found then
    raise exception 'Transaccion no encontrada';
  end if;

  if v_tx.estado = 'exitoso' then
    select * into v_membership
    from public.membresias_usuario
    where id_usuario = v_tx.id_usuario
      and id_plan_membresia = v_tx.id_plan_membresia
      and esta_activa = true
    order by fecha_fin desc
    limit 1;

    return jsonb_build_object(
      'already_finalized', true,
      'membership_id', v_membership.id,
      'membership_start', v_membership.fecha_inicio,
      'membership_end', v_membership.fecha_fin
    );
  end if;

  if v_tx.estado not in ('pendiente', 'procesando', 'pendiente_3ds') then
    raise exception 'La transaccion no puede finalizarse desde el estado %', v_tx.estado;
  end if;

  if v_tx.monto <> p_monto or upper(v_tx.moneda) <> upper(p_moneda) then
    raise exception 'El monto o la moneda no coinciden';
  end if;

  select * into v_plan
  from public.planes_membresia
  where id = v_tx.id_plan_membresia
    and esta_activo = true;

  if not found then
    raise exception 'Plan no encontrado';
  end if;

  if exists (
    select 1 from public.transacciones_pago
    where culqi_charge_id = p_culqi_charge_id
      and id <> v_tx.id
  ) then
    raise exception 'El cargo ya fue utilizado';
  end if;

  update public.transacciones_pago
  set estado = 'exitoso',
      culqi_charge_id = p_culqi_charge_id,
      culqi_card_brand = nullif(p_card_brand, ''),
      culqi_card_last4 = nullif(p_card_last4, ''),
      culqi_outcome_code = nullif(p_outcome_code, ''),
      culqi_request_id = nullif(p_request_id, ''),
      verificado_proveedor_en = v_now,
      fecha_pago = v_now,
      actualizado_en = v_now,
      culqi_token_id = null,
      respuesta_culqi = null,
      mensaje_error = null
  where id = v_tx.id;

  update public.membresias_usuario
  set esta_activa = false,
      actualizado_en = v_now
  where id_usuario = v_tx.id_usuario
    and esta_activa = true
    and fecha_fin < v_now;

  select * into v_membership
  from public.membresias_usuario
  where id_usuario = v_tx.id_usuario
    and id_plan_membresia = v_tx.id_plan_membresia
    and esta_activa = true
    and fecha_fin >= v_now
  order by fecha_fin desc
  limit 1
  for update;

  if found then
    v_start := v_membership.fecha_inicio;
    v_previous_end := v_membership.fecha_fin;
    v_end := v_membership.fecha_fin + make_interval(months => greatest(v_plan.duracion_meses, 1));
    v_action := 'renovacion';

    update public.membresias_usuario
    set fecha_fin = v_end,
        actualizado_en = v_now
    where id = v_membership.id
    returning * into v_membership;
  else
    v_start := v_now;
    v_end := v_now + make_interval(months => greatest(v_plan.duracion_meses, 1));
    v_action := 'activacion';

    insert into public.membresias_usuario (
      id_usuario,
      id_plan_membresia,
      fecha_inicio,
      fecha_fin,
      esta_activa
    ) values (
      v_tx.id_usuario,
      v_tx.id_plan_membresia,
      v_start,
      v_end,
      true
    )
    returning * into v_membership;
  end if;

  insert into public.historial_membresias (
    id_usuario,
    id_membresia,
    id_transaccion,
    accion,
    fecha_inicio_anterior,
    fecha_fin_anterior,
    fecha_inicio_nueva,
    fecha_fin_nueva,
    notas
  ) values (
    v_tx.id_usuario,
    v_membership.id,
    v_tx.id,
    v_action,
    case when v_action = 'renovacion' then v_start else null end,
    v_previous_end,
    v_start,
    v_end,
    'Pago Culqi verificado en servidor'
  );

  return jsonb_build_object(
    'already_finalized', false,
    'membership_id', v_membership.id,
    'membership_start', v_membership.fecha_inicio,
    'membership_end', v_membership.fecha_fin,
    'plan_name', v_plan.nombre
  );
end;
$$;

create or replace function public.crear_comprobante_pago(
  p_transaccion_id bigint,
  p_tipo_comprobante text,
  p_serie text,
  p_ambiente_sunat text,
  p_ruc_emisor text,
  p_razon_social_emisor text,
  p_tipo_documento_cliente text,
  p_numero_documento_cliente text,
  p_nombre_cliente text,
  p_direccion_cliente text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tx public.transacciones_pago%rowtype;
  v_existing public.comprobantes_electronicos%rowtype;
  v_receipt public.comprobantes_electronicos%rowtype;
  v_number bigint;
  v_subtotal numeric(12, 2);
  v_igv numeric(12, 2);
begin
  select * into v_tx
  from public.transacciones_pago
  where id = p_transaccion_id
  for update;

  if not found or v_tx.estado <> 'exitoso' then
    raise exception 'El pago no esta confirmado';
  end if;

  select * into v_existing
  from public.comprobantes_electronicos
  where id_transaccion = p_transaccion_id;

  if found then
    return to_jsonb(v_existing);
  end if;

  insert into public.series_comprobante (
    ruc_emisor,
    tipo_comprobante,
    serie,
    siguiente_numero
  ) values (
    p_ruc_emisor,
    upper(p_tipo_comprobante),
    upper(p_serie),
    2
  )
  on conflict (ruc_emisor, tipo_comprobante, serie)
  do update set
    siguiente_numero = public.series_comprobante.siguiente_numero + 1,
    actualizado_en = now()
  returning siguiente_numero - 1 into v_number;

  v_subtotal := round(v_tx.monto / 1.18, 2);
  v_igv := v_tx.monto - v_subtotal;

  insert into public.comprobantes_electronicos (
    id_usuario,
    id_transaccion,
    tipo_comprobante,
    serie,
    numero,
    ambiente_sunat,
    ruc_emisor,
    razon_social_emisor,
    tipo_documento_cliente,
    numero_documento_cliente,
    nombre_cliente,
    direccion_cliente,
    correo_cliente,
    moneda,
    subtotal,
    igv,
    total
  ) values (
    v_tx.id_usuario,
    v_tx.id,
    upper(p_tipo_comprobante),
    upper(p_serie),
    v_number,
    p_ambiente_sunat,
    p_ruc_emisor,
    p_razon_social_emisor,
    p_tipo_documento_cliente,
    p_numero_documento_cliente,
    p_nombre_cliente,
    nullif(p_direccion_cliente, ''),
    v_tx.correo_cliente,
    v_tx.moneda,
    v_subtotal,
    v_igv,
    v_tx.monto
  )
  returning * into v_receipt;

  return to_jsonb(v_receipt);
end;
$$;

revoke all on function public.finalizar_pago_culqi(bigint, text, numeric, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.crear_comprobante_pago(bigint, text, text, text, text, text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.finalizar_pago_culqi(bigint, text, numeric, text, text, text, text, text) to service_role;
grant execute on function public.crear_comprobante_pago(bigint, text, text, text, text, text, text, text, text, text) to service_role;
