-- Align existing bdsimulador schema with SimulaManejo frontend/backend needs.
-- This migration is intentionally additive and keeps the loaded question bank intact.

begin;

-- -----------------------------------------------------------------------------
-- Session/result compatibility fields
-- -----------------------------------------------------------------------------

alter table public.sesion_practica
  add column if not exists respuestas_incorrectas integer not null default 0,
  add column if not exists sin_responder integer not null default 0,
  add column if not exists porcentaje numeric(5,2),
  add column if not exists aprobado boolean,
  add column if not exists fecha_fin timestamptz,
  add column if not exists updated_at timestamptz,
  add column if not exists created_at timestamptz,
  add column if not exists ids_preguntas jsonb,
  add column if not exists tipo_sesion text,
  add column if not exists tiempo_total integer,
  add column if not exists preguntas_marcadas jsonb not null default '[]'::jsonb,
  add column if not exists respuestas_detalle jsonb not null default '[]'::jsonb,
  add column if not exists topic_breakdown jsonb not null default '[]'::jsonb;

update public.sesion_practica
set
  respuestas_incorrectas = greatest(coalesce(preguntas_respondidas, 0) - coalesce(respuestas_correctas, 0), 0),
  sin_responder = greatest(coalesce(total_preguntas, 0) - coalesce(preguntas_respondidas, 0), 0),
  porcentaje = coalesce(porcentaje, porcentaje_precision),
  aprobado = coalesce(aprobado, coalesce(porcentaje, porcentaje_precision, 0) >= 80),
  fecha_fin = coalesce(fecha_fin, hora_fin),
  updated_at = coalesce(updated_at, actualizado_en, now()),
  created_at = coalesce(created_at, creado_en, hora_inicio, now()),
  tipo_sesion = coalesce(tipo_sesion, modo_practica);

alter table public.intento
  add column if not exists id_sesion_practica integer references public.sesion_practica(id) on delete set null,
  add column if not exists id_categoria integer references public.categoria(id) on delete set null,
  add column if not exists tipo_intento text,
  add column if not exists total_preguntas integer,
  add column if not exists respuestas_correctas integer,
  add column if not exists respuestas_incorrectas integer,
  add column if not exists sin_responder integer,
  add column if not exists porcentaje numeric(5,2),
  add column if not exists aprobado boolean,
  add column if not exists respuestas_detalle jsonb not null default '[]'::jsonb,
  add column if not exists preguntas_marcadas jsonb not null default '[]'::jsonb,
  add column if not exists topic_breakdown jsonb not null default '[]'::jsonb,
  add column if not exists fecha_inicio timestamptz,
  add column if not exists fecha_fin timestamptz,
  add column if not exists created_at timestamptz not null default now();

update public.intento
set
  porcentaje = coalesce(porcentaje, puntuacion),
  aprobado = coalesce(aprobado, coalesce(porcentaje, puntuacion, 0) >= 80),
  fecha_inicio = coalesce(fecha_inicio, hora_inicio),
  fecha_fin = coalesce(fecha_fin, hora_fin),
  tipo_intento = coalesce(tipo_intento, 'CRONOMETRADO'),
  created_at = coalesce(created_at, hora_inicio, now());

-- -----------------------------------------------------------------------------
-- User settings and learning content
-- -----------------------------------------------------------------------------

create table if not exists public.configuracion_usuario (
  id_usuario integer primary key references public.usuarios(id) on delete cascade,
  categoria_preferida_id integer references public.categoria(id) on delete set null,
  notificaciones_habilitadas boolean not null default true,
  tema text not null default 'light',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.clases (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  titulo text not null,
  descripcion text,
  duracion_minutos integer not null default 0,
  total_lecciones integer not null default 0,
  orden integer not null default 0,
  esta_activa boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.lecciones_clase (
  id bigint generated by default as identity primary key,
  id_clase bigint not null references public.clases(id) on delete cascade,
  titulo text not null,
  descripcion text,
  duracion_minutos integer not null default 0,
  url_video text,
  orden integer not null default 0,
  esta_activa boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.progreso_clase_usuario (
  id_usuario integer not null references public.usuarios(id) on delete cascade,
  id_clase bigint not null references public.clases(id) on delete cascade,
  progreso_porcentaje integer not null default 0 check (progreso_porcentaje between 0 and 100),
  lecciones_completadas integer not null default 0,
  ultima_leccion_id bigint references public.lecciones_clase(id) on delete set null,
  actualizado_en timestamptz not null default now(),
  primary key (id_usuario, id_clase)
);

insert into public.clases (slug, titulo, descripcion, duracion_minutos, total_lecciones, orden)
values
  ('senales-transito', 'Señales de tránsito', 'Reconocimiento e interpretación de señales reglamentarias, preventivas e informativas.', 45, 6, 1),
  ('normas-circulacion', 'Normas de circulación', 'Reglas esenciales de preferencia, velocidad, carriles y maniobras seguras.', 55, 7, 2),
  ('manejo-defensivo', 'Manejo defensivo', 'Técnicas para anticipar riesgos y reducir incidentes en ciudad y carretera.', 50, 6, 3),
  ('primeros-auxilios', 'Primeros auxilios', 'Respuesta inicial ante siniestros, seguridad de escena y comunicación de emergencia.', 35, 4, 4),
  ('mecanica-basica', 'Mecánica básica', 'Controles preventivos, luces, neumáticos, frenos y mantenimiento inicial.', 40, 5, 5)
on conflict (slug) do update set
  titulo = excluded.titulo,
  descripcion = excluded.descripcion,
  duracion_minutos = excluded.duracion_minutos,
  total_lecciones = excluded.total_lecciones,
  orden = excluded.orden,
  actualizado_en = now();

-- -----------------------------------------------------------------------------
-- Reporting views
-- -----------------------------------------------------------------------------

create or replace view public.vw_ranking_usuarios as
select
  u.id as id_usuario,
  u.nombre_usuario,
  u.correo_electronico,
  coalesce(i.id_categoria, sp.id_categoria) as id_categoria,
  c.nombre as categoria,
  count(i.id) as intentos,
  round(avg(coalesce(i.porcentaje, i.puntuacion, sp.porcentaje, sp.porcentaje_precision, 0))::numeric, 2) as promedio,
  max(coalesce(i.fecha_fin, i.hora_fin, sp.fecha_fin, sp.hora_fin, i.created_at)) as ultimo_intento
from public.usuarios u
left join public.intento i on i.id_usuario = u.id
left join public.sesion_practica sp on sp.id = i.id_sesion_practica
left join public.categoria c on c.id = coalesce(i.id_categoria, sp.id_categoria)
group by u.id, u.nombre_usuario, u.correo_electronico, coalesce(i.id_categoria, sp.id_categoria), c.nombre;

create or replace view public.vw_resumen_usuario as
select
  u.id as id_usuario,
  count(i.id) as total_intentos,
  round(avg(coalesce(i.porcentaje, i.puntuacion, 0))::numeric, 2) as promedio_general,
  count(*) filter (where coalesce(i.aprobado, coalesce(i.porcentaje, i.puntuacion, 0) >= 80)) as intentos_aprobados,
  max(coalesce(i.fecha_fin, i.hora_fin, i.created_at)) as ultimo_intento
from public.usuarios u
left join public.intento i on i.id_usuario = u.id
group by u.id;

-- -----------------------------------------------------------------------------
-- Indexes for Edge Function lookups
-- -----------------------------------------------------------------------------

create index if not exists idx_usuarios_correo_electronico on public.usuarios (lower(correo_electronico));
create index if not exists idx_usuarios_nombre_usuario on public.usuarios (lower(nombre_usuario));
create index if not exists idx_users_email on public.users (lower(email));
create index if not exists idx_users_username on public.users (lower(username));
create index if not exists idx_sesion_practica_usuario on public.sesion_practica (id_usuario, creado_en desc);
create index if not exists idx_intento_usuario on public.intento (id_usuario, created_at desc);
create index if not exists idx_intento_categoria on public.intento (id_categoria);
create index if not exists idx_respuesta_intento_intento on public.respuesta_intento (id_intento);
create index if not exists idx_transacciones_pago_usuario on public.transacciones_pago (id_usuario, creado_en desc);
create index if not exists idx_libro_reclamaciones_numero on public.libro_reclamaciones (numero_reclamo);
create index if not exists idx_categoria_pregunta_categoria on public.categoria_pregunta (id_categoria);
create index if not exists idx_opcion_pregunta_pregunta on public.opcion_pregunta (id_pregunta);

commit;
